#!/bin/bash

# Nom : Hauwaert
# Prénom : Maxime
# Matricule : 461714

run() {
: '
  Parcourt les répertoires personnels du PoolV1
  Arguments :
    $1 Path_To_PoolV1
    $2 Path_To_PoolV2
    $3 Admin
    $4 Group
'
  if [ ! -e $2 ];then
    mkdir -p $2
  fi

  setPermissions $2 $3 $4 750 # 750 = rwxr-x---

  for dir in $1*/;do

    if [ -e $dir ];then
      dir_name=${dir#$1}
      owner=${dir_name%/}

      if ! id $owner >/dev/null 2>&1;then
      # Si le nom du répertoire personnel ne correspond pas à un utilisateur existant sur la machine
        owner=$(stat -c '%U' $dir)
      fi

      mkdir -p $2$owner
      setPermissions $2$owner $3 $4 750 # 750 = rwxr-x---
      poolV2_Creator $dir $2 $3 $4
    fi
  done
}

poolV2_Creator() {
: '
  Explore tout un répertoire du PoolV1 en créant le PoolV2
  Arguments :
    $1 Path_To_PoolV1
    $2 Path_To_PoolV2
    $3 Admin
    $4 Group
'
  for file in $1*;do

    if [ -d $file ];then
      poolV2_Creator $file/ $2 $3 $4

    elif [ -f $file ];then
      owner=$(stat -c '%U' $file)
      filename=${file#$1}
      name=${filename#*_}
      path=$2$5/
      time=${filename%_*}
      date=$(date -d @$time +"%Y %m %d")

      for temp in $owner $date;do
        path=$path$temp/
        mkdir -p $path
        setPermissions $path $3 $4 750 # 750 = rwxr-x---
      done

      cp $file $path
      mv $path$filename $path$name # Changement du nom du fichier
      setPermissions $path$name $owner $4 640 # 640 = rw-r-----
    fi
  done
}

setPermissions() {
: '
  Change les permissions du fichier en paramètre
  Arguments :
    $1 File
    $2 Owner
    $3 Group
    $4 Octal_Permission
'
  chown $2 $1
  chgrp $3 $1
  chmod $4 $1
}

if [ $EUID -ne 0 ];then
  echo "Root permissions required"
  exit 1
else
  run $@
fi
